### ISSUE TITLE
Plugin config is deployed to app directory

### ISSUE THREAD

**Issue by fiona-june-leathers** [Cloud-Harvest/CloudHarvestPluginAws#17]
Plungins should deploy default configuration files to the app directory.

Plugins load config files from the app directory. This allows us to set configurations (even long ones) without passing configs between the app and the plugin.

* How are these configs raised / reported to the API for the purpose of generating jobs?
* How do agents know the configurations of plugins?

**Comment by fiona-june-leathers** [comment]
Scrubbed this for another approach: embedding these configurations in the Agent `harvest.yaml`'

For example:

```yaml
########################################################################################################################
# Platform Configuration
# Tells the Agent which platforms and accounts which are available to it. The agent will only run TaskChains that are
# compatible with the designated platforms and accounts.
########################################################################################################################
platforms:
  aws:              # The platform name.
    accounts:       # The list of AWS accounts that this agent can access.
      - 123456789
      - 987654321
      - 111111111
      - 222222222
    role_name: harvest   # The role to assume when running tasks on this platform. This is applied to the role ARN when
                         # assuming the role. The role must be defined in the AWS account, such as: arn:aws:iam::123456789:role/harvest
```
